### ISSUE TITLE
bot suddenly stopped merging

### ISSUE THREAD

**Issue by dareojo** [bobvanderlinden/probot-auto-merge#366]
Probot auto merge suddenly stopped working today.

Kindly advise. Nothing has changed in the Repository..

Thank you

**Comment by bobvanderlinden** [comment]
You're absolutely right. There was a problem after upgrading to a new version of probot. It should be resolved now.

**Comment by dareojo** [comment]
It is still not auto-merging. Is there anything I have to do from my end? It started since yesterday

**Comment by ostrolucky** [comment]
It merged last PR for us `22 Aug 2019, 07:50 CEST`, but PR where we applied label `22 Aug 2019, 08:17 CEST` was not picked up

**Comment by dareojo** [comment]
It has stopped again :( Is there a way to make it work continuously and seamlessly?

**Comment by bobvanderlinden** [comment]
I've tried to fix the issues a few times. There were a few after upgrading to a new probot version. Those issues should've been resolved. In addition, I needed to do a few restarts of the Heroku instance. Every time that happens there is a chance PRs are skipped.

Please do note that probot-auto-merge is running on a free instance of Heroku, a single dyno. You may host your own if you'd like a potentially more stable solution.

**Comment by dareojo** [comment]
Thanks for the response. Does it upgrade automatically? Do you have steps for hosting it on our own heroku instance and creating a github app from it?

**Comment by bobvanderlinden** [comment]
yes it usually deploys auotmatically on commits on master, but because of the problems (and automatic merging of dev dependencies), I temporarily disabled that process.

**Comment by bobvanderlinden** [comment]
Unfortunately I've hit the limit of my free tier on Heroku today ☹️. I will probably pay for this month, but need to look into sponsorship.

**Comment by shepting** [comment]
@bobvanderlinden Could I Venmo you some money to help with the hosting costs? Ideally, in exchange you could get the `nixpkgs-ruby` working inside a `nixj-shell` environment? https://github.com/bobvanderlinden/nixpkgs-ruby/issues/1
